In [1]:
import pandas as pd
import numpy as np

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [1]:
import pandas as pd

merged_df = pd.read_csv('Processing data/TN/TN_allinone0112.csv')
merged_df.info()

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/tmp/ipykernel_25321/2031949268.py:3: DtypeWarning: Columns (6,11,16,18,22,23,25,26,28,29,31,32,34,36,37,39,41,42,45,46,49,50,53,54,57,58,61,62,63,64,65,66,67,68,69,70,71,72,73,115,116,129,130,131,153,154,158,159,163,164,168,171,173,178,179,180,181,182,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,206,207,208,209,212,213,214,215,216,217,219,224,226,228,230,231,232,233,235,239,240,241,242,243,244,246,247,248,249,250,254,285,286,292,293,295,296,297,298,299,301,303,304,305,306,308,311,314,318,320,323,325,326,329,331,333,335,336,337,339,344,349,350,352,353,354,355,356,357,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,394,396,397,398,400,401,402,405,406,408,410,411,414,417,418,419,513,514,515,516,517,518,519,520,521,522,523,524,525,526,530,537,541,542,543,546,547,548,549,550,551,552,553,554,555,556,557,558,559,562,563,564,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,583,584,585,586,588,589,590,591,592,594,595,597,599,600,602,604,605,607,608,609,610,612,613,614,615,617,618,620,621,622,623,624,625,626,627) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv('Processing data/TN/TN_allinone0112.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259064 entries, 0 to 259063
Columns: 708 entries, Unnamed: 0 to INS90
dtypes: float64(350), int64(2), object(356)
memory usage: 1.4+ GB

In [2]:
merged_df.shape

(259064, 708)

In [5]:
#identify categorical columns and numeric columns first 

categorical_columns = merged_df.select_dtypes(include=['object', 'category']).columns
numerical_columns = merged_df.select_dtypes(include=['int', 'float']).columns
print("Categorical columns:", categorical_columns)
print('number of categorical columns:',len(categorical_columns))
print("Numerical columns:", numerical_columns) 
print('number of numerical columns:',len(numerical_columns))

Categorical columns: Index(['Visit', 'Visit_Dt', '_15Aug2011ConsentForResidualSa',
       'WhichProtocolVersion', 'ProtocolVersion', 'Spring2019ConsentDateMonth',
       'DateOfBloodDrawMonth', 'DateReportedMonth',
       'DateResultsReportedByLabUnknow', 'RBCResultsNormal',
       ...
       'ParticipantDateDispensedMon3_1', 'ParticipantDateDispensedYea3_1',
       'ParticipantDateDispensedYea4_1', 'ParticipantDateDispensedDay5_1',
       'ParticipantDateDispensedYea5_1', 'UnusualCircumstances',
       'STHavetherebeenanychangesinhea', 'STHavetherebeenanychangesincon',
       'STIstheparticipantcurrentlytak', 'STWastheparticipantcontactedat'],
      dtype='object', length=356)
number of categorical columns: 356
Numerical columns: Index(['Unnamed: 0', 'MaskID', 'Spring2019ConsentDateDay',
       'Spring2019ConsentDateYear', 'DateOfBloodDrawDay',
       'DateOfBloodDrawYear', 'TimeOfCollectionHH', 'TimeOfCollectionMM',
       'DateReportedDay', 'DateReportedYear',
       ...
       'HLAa', 'HLAb', 'ICA512', 'GAD65', 'INS0', 'INS120', 'INS-10', 'INS60',
       'INS30', 'INS90'],
      dtype='object', length=352)
number of numerical columns: 352

In [6]:
numerical_columns

Index(['Unnamed: 0', 'MaskID', 'Spring2019ConsentDateDay',
       'Spring2019ConsentDateYear', 'DateOfBloodDrawDay',
       'DateOfBloodDrawYear', 'TimeOfCollectionHH', 'TimeOfCollectionMM',
       'DateReportedDay', 'DateReportedYear',
       ...
       'HLAa', 'HLAb', 'ICA512', 'GAD65', 'INS0', 'INS120', 'INS-10', 'INS60',
       'INS30', 'INS90'],
      dtype='object', length=352)

In [8]:
missing=[]
for i in numerical_columns:
    count_null=merged_df[i].isnull().sum()
    print(i)
    #print(count_null)
    all1=len(merged_df[i])
    #print(all)
    null_per=count_null/all1
    print(null_per*100,'%')
    if null_per*100<50:
        missing.append(i)

Unnamed: 0
0.0 %
MaskID
0.0 %
Spring2019ConsentDateDay
94.01615044930982 %
Spring2019ConsentDateYear
94.01615044930982 %
DateOfBloodDrawDay
99.22528795973196 %
DateOfBloodDrawYear
99.22528795973196 %
TimeOfCollectionHH
99.63792730753791 %
TimeOfCollectionMM
99.63831331254053 %
DateReportedDay
99.22528795973196 %
DateReportedYear
99.22528795973196 %
TimeResultsProcessedByLabHH
99.68077386282927 %
TimeResultsProcessedByLabMM
99.68077386282927 %
Rbcresults
99.2276039897477 %
HemoglobinResults
99.2276039897477 %
HematocritResults
99.2276039897477 %
MCVresults
99.2276039897477 %
PlateletCountResultsNormal
99.22837599975296 %
MCHresults
99.2276039897477 %
MCHCresults
99.23571009480283 %
WBCresults
99.2276039897477 %
NeutrophilsResults
99.60550288731741 %
NeutrophilsResultsOR
99.61515301238305 %
LymphocytesResults
99.59006268721242 %
LymphocytesResultsOR
99.60395886730691 %
MonocytesResults
99.59237871722819 %
MonocytesResultsOR
99.60434487230955 %
EosinophilsResults
99.59353673223606 %
EosinophilsResultsOR
99.60434487230955 %
BasophilsResults
99.59469474724393 %
BasophilsResultsOR
99.60704690732793 %
ScreeningDay
9.837723496896519 %
ScreeningYear
9.837723496896519 %
Age
9.89137819226137 %
DegreeOfRelative_1st
9.438208319179816 %
DegreeOfRelative_2ndor3rd
9.438208319179816 %
BirthYear
9.460210604329431 %
Race_AmericanIndianorAlaskaNat
9.438208319179816 %
Race_Asian
9.438208319179816 %
Race_BlackorAfricanAmerican
9.438208319179816 %
Race_NativeHawaiianorOtherPaci
9.438208319179816 %
Race_Refused
9.438208319179816 %
Race_Unknownornotreported
9.438208319179816 %
Race_White
9.400765833925208 %
FirstHearAboutTrialN_ExistingTri
9.438208319179816 %
FirstHearAboutTrialN_FamilyFrien
9.438208319179816 %
FirstHearAboutTrialN_Brochure
9.438208319179816 %
FirstHearAboutTrialN_Healthcarep
9.438208319179816 %
FirstHearAboutTrialN_Tollfreepho
9.438208319179816 %
FirstHearAboutTrialN_NewspaperMa
9.438208319179816 %
FirstHearAboutTrialN_Poster
9.438208319179816 %
FirstHearAboutTrialN_Camp
9.438208319179816 %
FirstHearAboutTrialN_MeetingPres
9.438208319179816 %
FirstHearAboutTrialN_RadioTV
9.438208319179816 %
FirstHearAboutTrialN_Internet
9.438208319179816 %
FirstHearAboutTrialN_Other
9.438208319179816 %
ConsentSignedDay
61.86463576567952 %
ConsentSignedYear
61.86540777568478 %
DateSignedInformedConsentFormD
92.29109409257944 %
DateSignedInformedConsentFormY
92.29109409257944 %
DateSignedNEWInformedConsentFo
59.75666244634531 %
DateSignedNEWInformedConsentFo3
59.75897847636106 %
clinicalcenternumber
65.76290028718772 %
ScreeningSiteNumber
30.971497390606185 %
NumOfRelativesWithT1D
18.287759009356762 %
AgeOfRelativeWithT1D1_1
16.31450143593861 %
AgeOfOnsetInRelativeWithT1D1_1
13.819751103974307 %
AgeRelativeWithT1DStartedIn1_1
16.38398233641108 %
AgeOfRelativeWithT1D2_1
84.66672328073372 %
AgeOfOnsetInRelativeWithT1D2_1
83.22962665596147 %
AgeRelativeWithT1DStartedIn2_1
84.0711175616836 %
AgeOfRelativeWithT1D3_1
96.04460673810333 %
AgeOfOnsetInRelativeWithT1D3_1
95.64547756538924 %
AgeRelativeWithT1DStartedIn3_1
95.87939659697989 %
AgeOfRelativeWithT1D4_1
98.88212951239848 %
AgeOfOnsetInRelativeWithT1D4_1
98.78987431677115 %
AgeRelativeWithT1DStartedIn4_1
98.85510916221475 %
AgeOfRelativeWithT1D5_1
99.63329524750641 %
AgeOfOnsetInRelativeWithT1D5_1
99.60395886730691 %
AgeRelativeWithT1DStartedIn5_1
99.63020720748541 %
AgeOfRelativeWithT1D6_1
99.86528425408393 %
AgeOfOnsetInRelativeWithT1D6_1
99.85447611401044 %
AgeRelativeWithT1DStartedIn6_1
99.86451224407868 %
AgeOfRelativeWithT1D7_1
99.94016922459316 %
AgeOfOnsetInRelativeWithT1D7_1
99.9455732946299 %
AgeRelativeWithT1DStartedIn7_1
99.95059135966402 %
DateConsentSignedDay
98.18114442763178 %
DateConsentSignedYear
98.18153043263442 %
SeatedArmBPSystolic
94.68162307383504 %
SeatedArmBPDiastolic
94.68625513386654 %
Weightkg
92.72033165549826 %
Weightlbs
99.1465429391965 %
Heightcm
93.33600963468487 %
Heightin
99.39204212086588 %
IsHeightMeasured
99.9984559799895 %
IsWeightMeasured
99.9984559799895 %
MechanisticSampleCollectionDay
98.58606367538523 %
MechanisticSampleCollectionYea
98.58722169039311 %
SamplesCollectionDay
97.59210079362629 %
SamplesCollectionYear
97.59248679862891 %
SeatedHeartRate
97.62375320384152 %
SeatedRespiratoryRate
97.67084581416175 %
Weight
99.92665904950128 %
Height
99.93283512954328 %
WeightKg
99.2306920297687 %
HeightCm
99.2430441898527 %
DateRecordedDD1
99.66996572275578 %
DateRecordedYYYY1
99.67035172775839 %
DateRecordedDD2
99.66957971775314 %
DateRecordedYYYY2
99.66996572275578 %
DateRecordedDD3
99.66957971775314 %
DateRecordedYYYY3
99.66996572275578 %
TotalOfHomeBloodGlucoseOver3Da
99.72053237809962 %
TotalOfHBGMonitoringsLessThan6
99.71976036809437 %
AvgRecordedFastingGlucosesmgdl
99.72979649816261 %
AvgAllRecordedGlucosesMgDL
99.72130438810487 %
LowestGlucosemgdl
99.720146373097 %
HighestGlucosemgdl
99.720146373097 %
AvgUnitsShortActingInsulin
99.69814408794738 %
AverageUnitsOfItermediateInsul
99.70123212796838 %
LastHbA1cDay
99.431028626131 %
LastHbA1cYear
99.31059506531204 %
LastHbA1cValue
99.30403298026742 %
IfSpecimensNotCollec_Other
99.94788932464564 %
OGTTTestStartTimeHrs
99.91816693944354 %
OGTTTestStartTimeMins
99.91816693944354 %
OGTTAmountConsumed
99.91855294444616 %
OGTTTimeToConsumeGlucola
99.91816693944354 %
MMTTTestStartTimeHrs
99.51131766667696 %
MMTTTestStartTimeMins
99.51170367167958 %
MMTTAmountConsumed
99.51093166167433 %
MMTTTimeToConsumeBoost
99.51247568168483 %
InsulinDoseLast24Hrs
99.65066547262452 %
AnthopometricsWeightKg
99.95869746471914 %
AnthopometricsHeightCM
99.95869746471914 %
SeatedArmBloodPressureSystolic
99.95869746471914 %
SeatedArmBloodPressureDiastoli
99.95869746471914 %
TemperatureDegreeCelcius
99.95869746471914 %
HeartRateBPM
99.95869746471914 %
RespiratoryRateBPM
99.95908346972176 %
WrittenInformedConsentDay
99.95753944971126 %
WrittenInformedConsentYear
99.95753944971126 %
DateOfBirthYear
99.95869746471914 %
Type1DiabetesDiagnosisDay
99.95869746471914 %
Type1DiabetesDiagnosisYear
99.95869746471914 %
RecentHbA1cDiagnosis
99.96062748973227 %
HbA1crecordDateYear
99.9610134947349 %
InterferonGammaReleaseAssayIGR
99.95869746471914 %
InterferonGammaReleaseAssayIGR2
99.95869746471914 %
FluVaccinationDateDay
99.95869746471914 %
FluVaccinationDateYear
99.95869746471914 %
ATGweight
99.96603155976902 %
ATGdose
99.96603155976902 %
PreInfusionTimeHour
99.96603155976902 %
PreInfusionTimeMin
99.96603155976902 %
PreInfusionSystolic
99.96603155976902 %
PreInfusionDiastolic
99.96603155976902 %
PreInfusionTemperature
99.96603155976902 %
PreInfusionHeartRate
99.96603155976902 %
PreInfusionRespRate
99.96603155976902 %
InfusionStartTimeHour
99.96834758978477 %
InfusionStartTimeMin
99.96834758978477 %
InfusionStartTimeSystolic
99.96834758978477 %
InfusionStartTimeDiastolic
99.96834758978477 %
InfusionStartTimeTemperature
99.96834758978477 %
InfusionStartTimeHeartrate
99.96834758978477 %
InfusionStartTimeResprate
99.96834758978477 %
_30MinAfteStartTimeHour
99.96641756477163 %
_30MinAfteStartTimeMin
99.96641756477163 %
_30MinAfteStartTimeSystolic
99.96641756477163 %
_30MinAfteStartTimeDiastolic
99.96641756477163 %
_30MinAfteStartTimeHeartRate
99.96641756477163 %
_30MinAfteStartTimeTemp
99.96641756477163 %
_30MinAfteStartTimeRespRate
99.96641756477163 %
_60MinAfteStartTimeHour
99.96641756477163 %
_60MinAfteStartTimemin
99.96641756477163 %
_60MinAfteStartTimeSystolic
99.96641756477163 %
_60MinAfteStartTimeDiastolic
99.96641756477163 %
_60MinAfteStartTimeHeartRate
99.96641756477163 %
_60MinAfteStartTimeTemp
99.96641756477163 %
_60MinAfteStartTimeRespRate
99.96641756477163 %
_90MinAfteStartTimehour
99.96641756477163 %
_90MinAfteStartTimeMin
99.96641756477163 %
_90MinAfteStartTimesystolic
99.96641756477163 %
_90MinAfteStartTimeHeartrate
99.96641756477163 %
_90MinAfteStartTimetemp
99.96641756477163 %
_90MinAfteStartTimeRespRate
99.96641756477163 %
_90MinAfteStartTimeDiastolic
99.96641756477163 %
_120MinAfteStartTimeHour
99.96641756477163 %
_120MinAfteStartTimeMin
99.96641756477163 %
_120MinAfteStartTimeSystolic
99.96641756477163 %
_120MinAfteStartTimeDiastolic
99.96641756477163 %
_120MinAfteStartTimeHeartRate
99.96641756477163 %
_120MinAfteStartTimeTemp
99.96641756477163 %
_120MinAfteStartTimeRespRate
99.96641756477163 %
_3HrsAftStartTimeHour
99.96641756477163 %
_3HrsAftStartTimeMin
99.96641756477163 %
_3HoursSystolic
99.96641756477163 %
_3HrsAftStartTimeDiastolic
99.96641756477163 %
_3HrsAftStartTimeHeartRate
99.96641756477163 %
_3HrsAftStartTimeTemp
99.96641756477163 %
_3HrsAftStartTimeRespRate
99.96641756477163 %
_4HrsAftStartTimeMissedHour
99.96641756477163 %
_4HrsAftStartTimeMin
99.96641756477163 %
_4HrsAftStartTimeSystolic
99.96641756477163 %
_4HrsAftStartTimeDiastolic
99.96641756477163 %
_4HrsAftStartTimeHeartRate
99.96641756477163 %
_4HrsAftStartTimeTemp
99.96641756477163 %
_4HrsAftStartTimeRespRate
99.96641756477163 %
_5HrsAftStartTimeHour
99.96603155976902 %
_5HrsAftStartTimeMin
99.96603155976902 %
_5HrsAftStartTimeSystolic
99.96603155976902 %
_5HrsAftStartTimeDiastolic
99.96603155976902 %
_5HrsAftStartTimeHeartRate
99.96603155976902 %
_5HrsAftStartTimeTemp
99.96603155976902 %
_5HrsAftStartTimeRespRate
99.96603155976902 %
_5HrsAftStartTimeHours
99.96603155976902 %
_6HrsAftStartTimeMin
99.96603155976902 %
_6HrsAftStartTimeSystolic
99.96603155976902 %
_6HrsAftStartTimeDiastolic
99.96603155976902 %
_6HrsAftStartTimeHeartRate
99.96603155976902 %
_6HrsAftStartTimeTemp
99.96603155976902 %
_6HrsAftStartTimeRespRate
99.96603155976902 %
_7HrsAftStartTimeHours
99.96603155976902 %
_7HrsAftStartTimeMin
99.96603155976902 %
_7HrsAftStartTimeSystolic
99.96603155976902 %
_7HrsAftStartTimeDiastolic
99.96603155976902 %
_7HrsAftStartTimeHeart
99.96603155976902 %
_7HrsAftStartTimeTemperature
99.96603155976902 %
_7HrsAftStartTimeRespRate
99.96603155976902 %
_8HrsAftStartTimeHours
99.96641756477163 %
_8HrsAftStartTimeMin
99.96641756477163 %
_8HrsAftStartTimeSystolic
99.96641756477163 %
_8HrsAftStartTimeDiastolic
99.96641756477163 %
_8HrsAftStartTimeHeartRate
99.96641756477163 %
_8HrsAftStartTimeTemp
99.96641756477163 %
_8HrsAftStartTimeRespRate
99.96641756477163 %
OtherHour1_1
99.97799771485039 %
OtherMin1_1
99.97799771485039 %
OtherSystolic1_1
99.97799771485039 %
OtherDiastolic1_1
99.97799771485039 %
OtherHeartRate1_1
99.97799771485039 %
OtherTemp1_1
99.97799771485039 %
OtherRespRate1_1
99.97799771485039 %
AcetaminophenGivenToPartici1_1
99.96603155976902 %
AcetaminophenGivenDoseTimeH1_1
99.96603155976902 %
AcetaminophenGivenDoseTimeM1_1
99.96603155976902 %
MethylprednisoneGivenDose1_1
99.96603155976902 %
MethylprednisoneGivenDoseTi1_1
99.96603155976902 %
MethylprednisoneGivenDoseTi1_2
99.96603155976902 %
MethylprednisoneGivenDose2_1
99.97220763981102 %
MethylprednisoneGivenDoseTi2_1
99.97220763981102 %
MethylprednisoneGivenDoseTi2_2
99.97220763981102 %
DiphenhydramineDoseGivenDos1_1
99.96641756477163 %
DiphenhydramineDosageTimeHo1_1
99.96641756477163 %
DiphenhydramineDosageTimeMi1_1
99.96641756477163 %
SpecificGravity
99.95753944971126 %
pH
99.95753944971126 %
DateTestsRunDay
99.73944662322823 %
DateTestsRunYear
99.73944662322823 %
bloodpressureSystolic
99.9285890745144 %
bloodpressureDiastolic
99.9285890745144 %
PreDoseGlucose
99.9656455547664 %
TimeDoseGivenMin
99.96603155976902 %
StudyDrugReturnedDay
99.89153259426243 %
CapsulesReturned
99.89153259426243 %
StudyDrugDispensedDay
99.89693666429918 %
CapsulesDispensed
99.89693666429918 %
RandomizationNumber
99.89732266930179 %
ParticipantDateDispensedDay1_1
99.90002470432017 %
ParticipantDateDispensedDay2_1
99.92472902448816 %
ParticipantDateDispensedDay3_1
99.95753944971126 %
ParticipantDateDispensedDay4_1
99.98417379489238 %
INST-10
16.68969829848995 %
PEP120
16.68969829848995 %
GLU60
16.68969829848995 %
PEP60
16.68969829848995 %
INST0
16.68969829848995 %
INST60
16.68969829848995 %
GLU30
16.68969829848995 %
PEP30
16.68969829848995 %
INST30
16.68969829848995 %
GLU0
16.68969829848995 %
HbA1c
16.68969829848995 %
PEP0
16.68969829848995 %
INST120
16.68969829848995 %
GLU-10
16.68969829848995 %
GLU90
16.68969829848995 %
PEP-10
16.68969829848995 %
PEP90
16.68969829848995 %
GLU120
16.68969829848995 %
INST90
16.68969829848995 %
GLU15
16.68969829848995 %
PEP15
16.68969829848995 %
EBVVCAIGG
16.68969829848995 %
PEP240
16.68969829848995 %
EBNA
16.68969829848995 %
GLU240
16.68969829848995 %
CMVIGM
16.68969829848995 %
HEPC
16.68969829848995 %
CMVIGG
16.68969829848995 %
ZNT8
16.68969829848995 %
ICA
16.68969829848995 %
PEP150
16.68969829848995 %
GLU180
16.68969829848995 %
IA-2H
16.68969829848995 %
GAD65H
16.68969829848995 %
PEP180
16.68969829848995 %
GLU150
16.68969829848995 %
PEP210
16.68969829848995 %
MIAA
16.68969829848995 %
EBVVL
16.68969829848995 %
CMVVL
16.68969829848995 %
HIV
16.68969829848995 %
HEPBC
16.68969829848995 %
HEPB
16.68969829848995 %
GLU210
16.68969829848995 %
EBVVCAIGM
16.68969829848995 %
CD8P
16.68969829848995 %
CD8A
16.68969829848995 %
CD4P
16.68969829848995 %
CD4CD8
16.68969829848995 %
CD4A
16.68969829848995 %
TPRO
16.68969829848995 %
TBIL
16.68969829848995 %
SOD
16.68969829848995 %
POT
16.68969829848995 %
GLU
16.68969829848995 %
GLOIgG
16.68969829848995 %
DBIL
16.68969829848995 %
CREA
16.68969829848995 %
CHL
16.68969829848995 %
BIC
16.68969829848995 %
ALT
16.68969829848995 %
ALP
16.68969829848995 %
ALB
16.68969829848995 %
UREA
16.68969829848995 %
AST
16.68969829848995 %
CPEP
16.68969829848995 %
INST
16.68969829848995 %
DR3
16.68969829848995 %
DR4
16.68969829848995 %
HLA
16.68969829848995 %
HLAa
16.68969829848995 %
HLAb
16.68969829848995 %
ICA512
16.68969829848995 %
GAD65
16.68969829848995 %
INS0
16.68969829848995 %
INS120
16.68969829848995 %
INS-10
16.68969829848995 %
INS60
16.68969829848995 %
INS30
16.68969829848995 %
INS90
16.68969829848995 %

In [ ]:
missing_above_50=[]
for i in numerical_columns:
    count_null=merged_df[i].isnull().sum()
    print(i)
    #print(count_null)
    all1=len(merged_df[i])
    #print(all)
    null_per=count_null/all1
    print(null_per*100,'%')
    if null_per*100>=50 and null_per*100<99:
        missing_above_50.append(i)

In [27]:
missing=missing[1:]

In [20]:
df = merged_df.drop(merged_df.columns[0], axis=1)

In [28]:
df[missing]

,MaskID,ScreeningDay,ScreeningYear,Age,DegreeOfRelative_1st,DegreeOfRelative_2ndor3rd,BirthYear,Race_AmericanIndianorAlaskaNat,Race_Asian,Race_BlackorAfricanAmerican,...,HLAa,HLAb,ICA512,GAD65,INS0,INS120,INS-10,INS60,INS30,INS90
0,200000,29.0,2007.0,20.0,0.0,1.0,1987.0,0.0,0.0,0.0,...,0.0,0.0,0.003,-0.002,0.0,0.0,0.0,0.0,0.0,0.0
1,200003,29.0,2015.0,20.0,1.0,0.0,1994.0,0.0,0.0,0.0,...,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
2,200004,11.0,2015.0,44.0,1.0,0.0,1970.0,0.0,0.0,0.0,...,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
3,200007,21.0,2016.0,7.0,1.0,0.0,2009.0,0.0,0.0,0.0,...,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
4,200010,21.0,2016.0,34.0,1.0,0.0,1982.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259059,999980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
259060,999981,17.0,2013.0,16.0,1.0,0.0,1997.0,0.0,0.0,0.0,...,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
259061,999985,12.0,2005.0,36.0,1.0,0.0,1968.0,0.0,1.0,0.0,...,0.0,0.0,0.001,0.001,0.0,0.0,0.0,0.0,0.0,0.0
259062,999987,13.0,2014.0,16.0,1.0,1.0,1998.0,0.0,0.0,0.0,...,0.0,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0
259063,999991,18.0,2020.0,6.0,1.0,1.0,2014.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
from sklearn.impute import KNNImputer
import pandas as pd
# Filter the DataFrame to include only the selected columns
df_to_impute = df[missing]

# Initialize the KNNImputer with the desired number of neighbors (k)
knn_imputer = KNNImputer(n_neighbors=5)  

# Perform K-NN imputation on the selected columns
df_imputed = knn_imputer.fit_transform(df_to_impute)

# The result will be a NumPy array; convert it back to a DataFrame with column names
df_imputed = pd.DataFrame(df_imputed, columns=df_to_impute.columns)

# Merge the imputed columns back into the original DataFrame
df[missing] = df_imputed

# Display the DataFrame with missing values imputed for selected columns
print(df)

In [15]:
merged_df['INS30']

0         0.0
1         0.0
2         0.0
3         0.0
4         NaN
         ...
259059    0.0
259060    0.0
259061    0.0
259062    0.0
259063    NaN
Name: INS30, Length: 259064, dtype: float64

In [12]:
len(merged_df['INS30'])

259064

In [13]:
43237/259064

0.1668969829848995

In [ ]:
from sklearn.impute import KNNImputer
import pandas as pd

# Assuming you have a DataFrame 'df' with numeric columns
# Replace 'df' with the actual name of your DataFrame

# Initialize the KNNImputer with the desired number of neighbors (k)
knn_imputer = KNNImputer(n_neighbors=5)  # You can adjust 'n_neighbors' as needed

# Perform K-NN imputation on the DataFrame
df_imputed = knn_imputer.fit_transform(df)

# The result will be a NumPy array; convert it back to a DataFrame with column names
df_imputed = pd.DataFrame(df_imputed, columns=df.columns)

# Display the DataFrame with missing values imputed
print(df_imputed)

In [186]:
df['SexOfRelativeWithT1D1_1']=df01['SexOfRelativeWithT1D1_1']
df['SexOfRelativeWithT1D2_1']=df01['SexOfRelativeWithT1D2_1']
df['SexOfRelativeWithT1D3_1']=df01['SexOfRelativeWithT1D3_1']
df['SexOfRelativeWithT1D4_1']=df01['SexOfRelativeWithT1D4_1']
df['SexOfRelativeWithT1D5_1']=df01['SexOfRelativeWithT1D5_1']
df['SexOfRelativeWithT1D6_1']=df01['SexOfRelativeWithT1D6_1']
df['SexOfRelativeWithT1D7_1']=df01['SexOfRelativeWithT1D7_1']

In [241]:
#Step1, check the values in this column

column_name='Weightkg'
value_counts = df[column_name].value_counts()
# Display the value counts
print(value_counts)
null_count = df[column_name].isnull().sum()
print(f"Number of null values in column '{column_name}': {null_count}")

Weightkg
136.072    2
193.700    2
145.900    2
209.720    1
441.960    1
          ..
310.520    1
164.974    1
419.700    1
206.360    1
151.840    1
Name: count, Length: 224, dtype: int64
Number of null values in column 'Weightkg': 197390

In [248]:
# Step 2, Create a mapping dictionary for month names to numbers

replacement_dict = {
    'FS=Brother/Sister': 7,
    'CH=Child': 6,
    'P=Parent': 9,
    'C=Cousin': 3,
    'GP=Grandparent': 5,
    'AU=Aunt/Uncle': 6,
    'HS=Half Brother/Sister': 4,
    'NT=Non-identical Twin': 10,
    'N=Niece/Nephew': 2,
    'IT=Identical Twin': 8,
    'HC=Half-Cousin': 1,
    None: 0
}

In [132]:
#df = df.dropna(subset=['BirthMonth'])

In [254]:
list(replacement_dict.keys())

['FS=Brother/Sister',
 'CH=Child',
 'P=Parent',
 'C=Cousin',
 'GP=Grandparent',
 'AU=Aunt/Uncle',
 'HS=Half Brother/Sister',
 'NT=Non-identical Twin',
 'N=Niece/Nephew',
 'IT=Identical Twin',
 'HC=Half-Cousin',
 None]

In [253]:
replacement_dict.values()

dict_values([7, 6, 9, 3, 5, 6, 4, 10, 2, 8, 1, 0])

In [133]:
#df = df.drop('Age', axis=1)

In [140]:
#Step 3, replace values according to replacement_dict

replacement_dict = {'Male':1,'Female':0, None:0.5}
df[column_name] = df[column_name].replace(replacement_dict)

In [242]:
# this is to handle numerical column, find the mean

average_value = df[column_name].mean()
print(average_value)

300.78094273127755

In [153]:
# this is to handle numerical column, find the mean

average_value = df[column_name].mean()
print(average_value)

15.907859749370598

In [155]:
# this is to handle numerical column, find the mean

average_value = df[column_name].mean()
print(average_value)

15.813345593732247

In [239]:
#Step 4, fill the null with value, and change the dtype to int

df[column_name].fillna(66.55, inplace=True)

# Change the column data type to int
df[column_name] = df[column_name].astype(float)

In [128]:
#embed=[]

In [142]:
#Step 5, add the dictionary into a list 

embed.append({'Column':column_name,'Details':replacement_dict})

In [102]:
#embed.pop()

In [214]:
#Step 6, check if the dictionary into the list

print(embed)

[{'Column': 'Sex', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'RelativeWithT1D', 'Details': {'Yes': 1, 'No': 0, None: 0.5}}, {'Column': 'BirthMonth', 'Details': {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6, 'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12}}, {'Column': 'Ethnicity', 'Details': {'Not Hispanic or Latino': 1, 'Hispanic or Latino': 0, 'Unknown': 0.5, None: 0.5}}, {'Column': 'BloodTestForFindOut', 'Details': {'I have autoantibodies which means I am at risk of getting Type 1 diabetes': 1, 'I have Type 1 diabetes': 2, 'I don?t know': 0, 'I have Type 2 diabetes': 3, None: 0}}, {'Column': 'RelativeWithT1D1_1', 'Details': {'FS=Brother/Sister': 7, 'CH=Child': 6, 'P=Parent': 9, 'C=Cousin': 3, 'GP=Grandparent': 5, 'AU=Aunt/Uncle': 6, 'HS=Half Brother/Sister': 4, 'NT=Non-identical Twin': 10, 'N=Niece/Nephew': 3, 'IT=Identical Twin': 8, 'HC=Half-Cousin': 2, None: 0}}, {'Column': 'SexOfRelativeWithT1D1_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'RelativeWithT1D2_1', 'Details': {'FS=Brother/Sister': 7, 'CH=Child': 6, 'P=Parent': 9, 'C=Cousin': 3, 'GP=Grandparent': 5, 'AU=Aunt/Uncle': 6, 'HS=Half Brother/Sister': 4, 'NT=Non-identical Twin': 10, 'N=Niece/Nephew': 3, 'IT=Identical Twin': 8, 'HC=Half-Cousin': 2, None: 0}}, {'Column': 'RelativeWithT1D3_1', 'Details': {'FS=Brother/Sister': 7, 'CH=Child': 6, 'P=Parent': 9, 'C=Cousin': 3, 'GP=Grandparent': 5, 'AU=Aunt/Uncle': 6, 'HS=Half Brother/Sister': 4, 'NT=Non-identical Twin': 10, 'N=Niece/Nephew': 3, 'IT=Identical Twin': 8, 'HC=Half-Cousin': 2, None: 0}}, {'Column': 'RelativeWithT1D4_1', 'Details': {'FS=Brother/Sister': 7, 'CH=Child': 6, 'P=Parent': 9, 'C=Cousin': 3, 'GP=Grandparent': 5, 'AU=Aunt/Uncle': 6, 'HS=Half Brother/Sister': 4, 'NT=Non-identical Twin': 10, 'N=Niece/Nephew': 2, 'IT=Identical Twin': 8, 'HC=Half-Cousin': 1, None: 0}}, {'Column': 'RelativeWithT1D5_1', 'Details': {'FS=Brother/Sister': 7, 'CH=Child': 6, 'P=Parent': 9, 'C=Cousin': 3, 'GP=Grandparent': 5, 'AU=Aunt/Uncle': 6, 'HS=Half Brother/Sister': 4, 'NT=Non-identical Twin': 10, 'N=Niece/Nephew': 2, 'IT=Identical Twin': 8, 'HC=Half-Cousin': 1, None: 0}}, {'Column': 'RelativeWithT1D6_1', 'Details': {'FS=Brother/Sister': 7, 'CH=Child': 6, 'P=Parent': 9, 'C=Cousin': 3, 'GP=Grandparent': 5, 'AU=Aunt/Uncle': 6, 'HS=Half Brother/Sister': 4, 'NT=Non-identical Twin': 10, 'N=Niece/Nephew': 2, 'IT=Identical Twin': 8, 'HC=Half-Cousin': 1, None: 0}}, {'Column': 'RelativeWithT1D7_1', 'Details': {'FS=Brother/Sister': 7, 'CH=Child': 6, 'P=Parent': 9, 'C=Cousin': 3, 'GP=Grandparent': 5, 'AU=Aunt/Uncle': 6, 'HS=Half Brother/Sister': 4, 'NT=Non-identical Twin': 10, 'N=Niece/Nephew': 2, 'IT=Identical Twin': 8, 'HC=Half-Cousin': 1, None: 0}}, {'Column': 'SexOfRelativeWithT1D2_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D3_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D4_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D5_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D6_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D7_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D2_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D3_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D4_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D5_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D6_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'SexOfRelativeWithT1D7_1', 'Details': {'Male': 1, 'Female': 0, None: 0.5}}, {'Column': 'AsthmaEver', 'Details': {'Yes': 1, 'No': 0, None: 0}}, {'Column': 'AsthmaWithinLastYear', 'Details': {'Yes': 1, 'No': 0, None: 0}}, {'Column': 'CeliacDiseaseEver', 'Details': {'Yes': 1, 'No': 0, None: 0}}, {'Column': 'CeliacDiseaseWithinLastYear', 'Details': {'Yes': 1, 'No': 0, None: 0}}, {'Column': 'InflammatoryBowelDiseaseEver', 'Details': {'Yes': 1, 'No': 0, None: 0}}]

In [201]:
#Step1, check the values in this column

column_name='SexOfRelativeWithT1D7_1'

replacement_dict = {'Male':1,'Female':0, None:0.5}
df[column_name] = df[column_name].replace(replacement_dict)

#Step 4, fill the null with value, and change the dtype to int
# Change the column data type to int
df[column_name] = df[column_name].astype(float)
df[column_name].fillna(0.5, inplace=True)

embed.append({'Column':column_name,'Details':replacement_dict})

In [ ]:
#Step1, check the values in this column

column_name='OtherAutoimmuneDiseasesWithinL'

replacement_dict = {'Yes':1,'No':0, None:0}
df[column_name] = df[column_name].replace(replacement_dict)

#Step 4, fill the null with value, and change the dtype to int
# Change the column data type to int
df[column_name] = df[column_name].astype(float)
df[column_name].fillna(0, inplace=True)

#Step 5, add the dictionary into a list 

embed.append({'Column':column_name,'Details':replacement_dict})

In [243]:
df.to_csv('AI TN01 in process hu', index=False)

In [244]:
# Define the file path where you want to save the text file
file_path = "embed_hu.txt"

# Open the file in write mode and save the list elements to it
with open(file_path, "w") as file:
    for item in embed:
        file.write("%s\n" % item)