In [1]:
import pandas as pd
import os

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
#load all data
df01=pd.read_csv('merged_output_01.csv')
#print(df01.shape)
df16=pd.read_csv('merged_output_16.csv')
print(df16.shape)
df19=pd.read_csv('merged_output_19.csv')
print(df19.shape)
df20=pd.read_csv('merged_output_20.csv')
print(df20.shape)

/tmp/ipykernel_11828/1299768904.py:2: DtypeWarning: Columns (3,8,16,17,18,19,23,28,30,37,38,39,40,41,42,49,57,60,63,66,68,69,73,74,78,79,80,81,82,83,84,85,86,89,91,98,103,110,111,114,115,118,119,122,123,126,127,130,131,134,135,138,139,143,144,148,149,153,154,158,159,163,164,167,169,170,171,172,173,174,176,178,179,180,181,183,186,187,189,190,193,194,195,197,198,199,202,203,204,206,207,213,214,218,219,220,221,222,223,224,225,226,228,230,231,233,235,237,239,241,243,245,247,249,252,254,256,258,259,264,265,271,280,292,293,294,296,307,308,309,310,311,312,313,314,315,316,317,318,319,320,322,325,326,327,328,331,332,333,334,338,339,340,341,345,346,347,348,352,353,354,355,399,400,413,414,415,432,437,438,442,443,447,448,452,453,457,458,462,463,464,468,469,470,474,475,476,477,478,479,480,481,482,483,488,489,496,500,506,508,510,512,522,524,526,529,530,531,533,535,537,542,546,547,548,549,550,553,557,560,561,563,565,566,567,568,569,570,571,577,586,595,596,597,598,599,601,602,603,604,605,606,607,608,609,610,611,612,613,614,616,617,618,619,620,621,622,623,624,625,626,627,635,642,643,644,650,652,653,655,658,660,663,665,666,668,669,671,672,674,675,677,678,682,683,686,690,693,697,700,704,707,711,714,718,721,725,728,732,734,735,737,741,743,744,746,750,752,753,755,759,761,762,764,768,770,771,773,777,779,780,782,786,788,789,791,795,797,798,800,804,806,807,809,811,813,814,819,821,823,826,828,831,833,836,838,841,843,846,847,849,852,854,858,861,863,867,870,872,875,876,878,881,882,884,887,888,890,893,895,897,898,899,901,903,904,905,907,909,910,911,913,915,916,917,919,921,922,923,924,926,928,930,932,934,936,938,940,942,945,947,950,952,955,957,960,962,963,964,965,966,967,968,970,972,973,974,975,976,977,978,979,980,981,982,983,991,994,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1149,1151,1152,1154,1159,1161,1162,1163,1164,1174) have mixed types. Specify dtype option on import or set low_memory=False.
  df01=pd.read_csv('merged_output_01.csv')

(952, 242)
(119, 821)
(115, 834)

In [5]:
#replace TNXX column name as TNXX_ index, save the list into TNXX column names

df16_column=df16.columns.tolist()
new_column_names = ["TN16_" + str(i) for i in range(len(df16_column))]
df16.columns = new_column_names
df16.rename(columns={df16.columns[0]: 'MaskID'}, inplace=True)
file_path="TN16 column names"
with open(file_path, 'w') as file:
    for item in df16_column:
        file.write(f"{item}\n")
print(f"List saved to {file_path}")


df01_column=df01.columns.tolist()
new_column_names = ["TN01_" + str(i) for i in range(len(df01_column))]
df01.columns = new_column_names
df01.rename(columns={df01.columns[0]: 'MaskID'}, inplace=True)
file_path="TN01 column names"
with open(file_path, 'w') as file:
    for item in df01_column:
        file.write(f"{item}\n")
print(f"List saved to {file_path}")


df19_column=df19.columns.tolist()
new_column_names = ["TN19_" + str(i) for i in range(len(df19_column))]
df19.columns = new_column_names
df19.rename(columns={df19.columns[0]: 'MaskID'}, inplace=True)
file_path="TN19 column names"
with open(file_path, 'w') as file:
    for item in df19_column:
        file.write(f"{item}\n")
print(f"List saved to {file_path}")


df20_column=df20.columns.tolist()
# Replace the column names with "TN01_" + index
new_column_names = ["TN20_" + str(i) for i in range(len(df20_column))]
df20.columns = new_column_names
df20.rename(columns={df20.columns[0]: 'MaskID'}, inplace=True)
file_path="TN20 column names"
with open(file_path, 'w') as file:
    for item in df20_column:
        file.write(f"{item}\n")
print(f"List saved to {file_path}")

List saved to TN16 column names
List saved to TN01 column names
List saved to TN19 column names
List saved to TN20 column names

In [6]:
print(df01['MaskID'].dtype)
print(df16['MaskID'].dtype)
print(df19['MaskID'].dtype)
print(df20['MaskID'].dtype)

int64
object
int64
int64

In [9]:
# Attempt to convert 'MaskID' to int64, drop rows with conversion errors, and print them
try:
    df16['MaskID'] = df16['MaskID'].astype('int64')
except ValueError as e:
    error_indices = df16.index[df16['MaskID'].apply(lambda x: not x.isdigit())]
    error_rows = df16.loc[error_indices]
    print("Rows with 'MaskID' conversion errors:")
    print(error_rows)
    df16.drop(error_indices, inplace=True)
    
print(df01['MaskID'].dtype)
print(df16['MaskID'].dtype)
print(df19['MaskID'].dtype)
print(df20['MaskID'].dtype)

int64
int64
int64
int64

In [10]:
# Merge the DataFrames sequentially with 'MaskID' as the primary key
merged_df = df16.merge(df19, on='MaskID', how='outer') \
    .merge(df20, on='MaskID', how='outer') \
    .merge(df01, on='MaskID', how='outer')

In [24]:
merged_df.to_csv('merged_df.csv',index=False)

In [25]:
maskid_values = df01['MaskID'].tolist()

file_path = 'TN01_maskid_list.txt'

# Save the list to a text file
with open(file_path, 'w') as file:
    for maskid in maskid_values:
        file.write(str(maskid) + '\n')

print(f'MaskID values saved to {file_path}')

MaskID values saved to TN01_maskid_list.txt

In [6]:
#replace TNXX column name as TNXX_ index, save the list into TNXX column names

df16_column=df16.columns.tolist()
new_column_names = ["TN16_" + str(i) for i in range(len(df16_column))]
df16.columns = new_column_names
df16.rename(columns={df16.columns[0]: 'MaskID'}, inplace=True)
#file_path="TN16 column names"
#with open(file_path, 'w') as file:
#    for item in df16_column:
#        file.write(f"{item}\n")
#print(f"List saved to {file_path}")

df16.head(16)

,MaskID,TN16_1,TN16_2,TN16_3,TN16_4,TN16_5,TN16_6,TN16_7,TN16_8,TN16_9,...,TN16_232,TN16_233,TN16_234,TN16_235,TN16_236,TN16_237,TN16_238,TN16_239,TN16_240,TN16_241
0,200608,03/15/2019,PRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2-hr OGTT -10 min insulin,S5885921,INST-10,2.1,RPTD,07/07/2016,07/06/2016,07/01/2016,06/30/2016,447.0
1,204914,10/10/2016,PRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2-hr OGTT 90 min glucose,S0306339,GLU90,259,RPTD,11/17/2015,11/16/2015,11/13/2015,11/12/2015,447.0
2,206881,08/20/2018,Initial Visit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2-hr MMTT 60 min c-peptide,S9790846,PEP60,.6,RPTD,08/23/2018,08/22/2018,08/21/2018,08/20/2018,447.0
3,207837,10/20/2014,PRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S0368259,HbA1c,9.1,RPTD,01/08/2013,01/08/2013,01/08/2013,01/07/2013,447.0
4,208756,06/16/2016,Initial Visit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S8220052,HbA1c,7.3,RPTD,06/24/2016,06/23/2016,06/23/2016,06/22/2016,447.0
5,209846,01/10/2020,PRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S8906646,HbA1c,7,RPTD,07/21/2014,07/18/2014,07/18/2014,07/17/2014,447.0
6,210642,08/07/2019,PRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S9866703,HbA1c,11.1,RPTD,08/13/2014,08/12/2014,08/12/2014,08/11/2014,447.0
7,211730,01/11/2019,PRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S9979558,HbA1c,6.2,RPTD,08/11/2016,08/10/2016,08/10/2016,08/09/2016,447.0
8,211928,01/10/2020,PRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S3915965,HbA1c,9.4,RPTD,02/15/2018,02/14/2018,02/13/2018,02/13/2018,447.0
9,212657,08/27/2014,Initial Visit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2-hr OGTT -10 min c-peptide,S5678226,PEP-10,3.47,RPTD,08/29/2014,08/28/2014,08/28/2014,08/27/2014,447.0
10,214098,08/21/2013,Initial Visit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2-hr MMTT 0 min c-peptide,S9939576,PEP0,.05,RPTD,08/26/2013,08/23/2013,08/22/2013,08/21/2013,447.0
11,214151,02/09/2018,PRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S5935071,HbA1c,8,RPTD,04/18/2013,04/17/2013,04/17/2013,04/16/2013,447.0
12,214715,09/18/2018,PRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S1353254,HbA1c,8.2,RPTD,10/05/2015,10/02/2015,10/02/2015,09/30/2015,447.0
13,216063,12/20/2016,Initial Visit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S6691298,HbA1c,5.6,RPTD,12/22/2016,12/21/2016,12/21/2016,12/20/2016,447.0
14,217140,12/19/2018,Initial Visit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S4487337,HbA1c,8.3,RPTD,12/20/2018,12/20/2018,12/20/2018,12/19/2018,447.0
15,218505,05/17/2018,PRN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Whole Blood - HbA1c,S5305342,HbA1c,7,RPTD,10/22/2014,10/21/2014,10/21/2014,10/20/2014,447.0